baseURL = "/"
title = "Cloudpods"

enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/zh"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "UA-00000000-0"

# Language configuration

[languages]
[languages.zh]
title = "Cloudpods"
languageName ="中文"
contentDir = "content/zh"
[languages.zh.params]
view_text = "点击查看"
version_menu = "版本"
description = "Cloudpods文档"
time_format_default = "02.01.2006"
time_format_blog = "02.01.2006"

# Additional menu items
[[languages.zh.menu.main]]
    name = "快速开始"
    weight = -100
    url = "docs/quickstart/"

# Additional menu items
[[languages.zh.menu.main]]
    name = "服务订阅"
    weight = 21
    url = "https://www.yunion.cn/subscription/index.html"

[[languages.zh.menu.main]]
    name = "GitHub"
    url = "https://github.com/yunionio/cloudpods"
    pre = "<i class='fab fa-github'></i>"
    weight = 50

#[[languages.zh.menu.main]]
#    name = "CHANGELOG"
#    weight = 59
#    url = "docs/changelog"

#[[languages.zh.menu.main]]
#    name = "联系我们"
#    weight = 60
#    url = "docs/contact"

[[languages.zh.menu.main]]
    name = "API"
    url = "docs/swagger"
    weight = 70

[languages.en]
languageName = "English"
contentDir = "content/en"
[languages.en.params]
version_menu = "Version"
description = "Documentation for Cloudpods"
time_format_default = "02.01.2006"
time_format_blog = "02.01.2006"

[[languages.en.menu.main]]
    name = "Quick Start"
    weight = -100
    url = "docs/quickstart/"

[[languages.en.menu.main]]
    name = "GitHub"
    url = "https://github.com/yunionio/cloudpods"
    pre = "<i class='fab fa-github'></i>"
    weight = 50

#[[languages.en.menu.main]]
#    name = "CHANGELOG"
#    weight = 59
#    url = "docs/changelog"

#[[languages.en.menu.main]]
#    name = "Contact us"
#    weight = 60
#    url = "docs/contact"

[[languages.en.menu.main]]
    name = "API"
    url = "docs/swagger"
    weight = 70

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      style = "tango"
      # Uncomment if you want chosen highlight style used for code blocks without a specified language
      # guessSyntax = "true"

### Everything below this are Site Params ###

[params]
oem = "cloudpods"
oem_name = "Cloudpods"
pre_release_version = "v3.9.14"
release_version = "v3.10.7"
release_branch = "release/3.10"
copyright = "The Cloudpods Authors."
icp_code = "京ICP备2021005745号-3"
is_ee = false
view_text = "Click to view"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"
multi_versions = true

RSSLink = "/index.xml"
author = "cloudpods.org" # add your company name
github = "yunionio" # add your github profile name
twitter = "yunionio" # add your twitter profile
github_repo = "https://github.com/yunionio/docs"
github_project_repo = "https://github.com/yunionio/cloudpods"
email = "info@cloudpods.org"

# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = "011737558837375720776:fsdu1nryfng"

# Enable Lunr.js offline search
offlineSearch = true

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = false

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/yunionio/docs/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/yunionio/docs/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page,
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = false

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_', 'CURRENT_VERSION', 'CONTENT_DIR', 'VERSIONS']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
